[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["GastonAQS <31553863+GastonAQS@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a_o_c_1 = {path = "a_o_c_1"}

[workspace]
